### ISSUE TITLE
Don't Working for me bro :(

### ISSUE THREAD

**Issue by Arturo-Cuevas-Perez** [prafulla-codes/face-recognition-login-system#3]
![image](https://user-images.githubusercontent.com/69091401/95009241-18b40500-05e6-11eb-9e94-6bea7168a7ff.png)
What do I need to make it work? I already install anaconda 3 and running on XAMMP server.

I'm new to this, I just want to try to run your application, sorry.
Im using Windows.

**Comment by Pika1998** [comment]
@Arturo-Cuevas-Perez Thank you for letting me know, I will get back to you soon

**Comment by Pika1998** [comment]
@Arturo-Cuevas-Perez  you have to go the login file not the python file
In your case it would be `https://localhost/face-login/login.html`

1. Start XAMPP
2. Make sure you have cloned this repo in htdocs folder
3. Then go to  [https://localhost/face-login/login.html](https://localhost/face-login/login.html) from your browser

**Comment by vasujain314** [comment]
@Pika1998  I followed the same steps and its not working

> @Arturo-Cuevas-Perez you have to go the login file not the python file
> In your case it would be `https://localhost/face-login/login.html`
> 
> 1. Start XAMPP
> 2. Make sure you have cloned this repo in htdocs folder
> 3. Then go to  https://localhost/face-login/login.html from your browser

**Comment by Pika1998** [comment]
@vasujain314 is there any particular error being shown?

**Comment by vasujain314** [comment]
> @vasujain314 is there any particular error being shown?

Instead of executing login.py the code is getting displayed on clicking log in button.

**Comment by Pika1998** [comment]
Ok please wait for sometime, i will get back to you

**Comment by Pika1998** [comment]
Thank you for reporting this issue, it seems there are more steps involved in setting up this project which haven't been documented in the README.md

My deepest apologies, I will fix it at the earliest possible

**Comment by Pika1998** [comment]
Hey @vasujain314  @Arturo-Cuevas-Perez Please check the latest updated code & the updated instructions in README.md

**Comment by Arturo-Cuevas-Perez** [comment]
@Pika1998 Hey hello bro, i have a new error, I think that I am already one step away from running the app. I get this error when I send my face and mail to be processed.
[
![WhatsApp Image 2020-11-08 at 6 50 31 PM](https://user-images.githubusercontent.com/69091401/98561979-1e4cdc80-226f-11eb-931a-ef6ec78b6710.jpeg)
](url)
If simple Python files with embedded HTML run fine, but the file you created for facial recognition does not work for me, I get that Internal Server Error.

![WhatsApp Image 2020-11-08 at 6 44 19 PM](https://user-images.githubusercontent.com/69091401/98562683-edb97280-226f-11eb-9d48-689d821cd84b.jpeg)

![WhatsApp Image 2020-11-08 at 6 43 54 PM](https://user-images.githubusercontent.com/69091401/98562716-f611ad80-226f-11eb-926a-126811ed0e85.jpeg)

Could you guide me to implement your project? I appreciate it bro.

**Comment by Arturo-Cuevas-Perez** [comment]
@Pika1998 These are the other settings. I already use XAMPP and WAMP, and with neither that configuration works for me in the httpd.conf file.
![WhatsApp Image 2020-11-08 at 6 49 37 PM](https://user-images.githubusercontent.com/69091401/98563147-746e4f80-2270-11eb-8918-2c481b3559d0.jpeg)

![WhatsApp Image 2020-11-08 at 6 46 14 PM](https://user-images.githubusercontent.com/69091401/98563194-8223d500-2270-11eb-899a-8f085c298724.jpeg)

![WhatsApp Image 2020-11-08 at 6 47 43 PM](https://user-images.githubusercontent.com/69091401/98563252-8f40c400-2270-11eb-9c2f-6f9972f9d247.jpeg)

![WhatsApp Image 2020-11-08 at 6 49 06 PM](https://user-images.githubusercontent.com/69091401/98563276-94057800-2270-11eb-9b29-459df6a362d7.jpeg)

**Comment by Pika1998** [comment]
@Arturo-Cuevas-Perez thank you so much for letting me know, I'll get back to you.

Actually even I don't remember how I had implementated this project now, it's been a long time 😅 I'll just try to get it work myself first and let you know 😇

**Comment by Arturo-Cuevas-Perez** [comment]
Yes, thank you very much friend, I hope your solution soon.

**Comment by Arturo-Cuevas-Perez** [comment]
@Pika1998 What's up bro. Could you already remember how the project works? I already want to implement it :( Thanks.

**Comment by Arturo-Cuevas-Perez** [comment]
I found the solution to the previous errors, but now I have the same error as the other person who opened the issue 'NoneType' object has no attribute 'split'.

![image](https://user-images.githubusercontent.com/69091401/99197881-d809e880-275a-11eb-8572-d5446ae76f04.png)

**Comment by asim266** [comment]
@Arturo-Cuevas-Perez I'm facing infernal server error 500 could you explain how did you found solution to this problem?

**Comment by shintogvarghese** [comment]
Hi, @prafulla-codes were you able to find the solution? It would be really great if you could. Thanks and Regards

**Comment by prafulla-codes** [comment]
Hi Everyone,

Apologies, but I am unable to find time to maintain this project, has anyone found the solution for this one.

I remember that i created this project on a linux machine 
https://face-recognition.readthedocs.io/en/latest/readme.html#installation

Also found in docs that windows isn't officially supported for the library which I have used
![image](https://user-images.githubusercontent.com/36433104/136685083-8d11cf89-8178-4066-b019-916945317e7c.png)

Maybe following the windows 10 guide may help while installing the library.

**Comment by prafulla-codes** [comment]
Hi @shintogvarghese , @asim266 , @Arturo-Cuevas-Perez , @vasujain314 
Thank you for raising this issue, I have updated the README file with the solution for making this project work on windows in the repositroy.

I've tried and tested the solution, hence closing this issue.
Feel free to reach out to me in case of any doubts.
